config/routes.rb
Rsfk::Application.routes.draw do
  
  match '/home', :to => 'pages#home'

  match '/registration', :to => 'pages#registration'

  match '/contact', :to => 'pages#contact'
  
  match '/admin', :to => 'pages#admin'
  
  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def registration
    @title = "Registration"
  end

  def contact
    @title = "Contact"
  end
  
  def admin
    @title = "Admin"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis.
    def title
      base_title = "GLIDING ON ICE 2011 ®"
      if @title.nil?
        base_title
      else
        "#{base_title} | #{@title}"
      end
    end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><a href="http://badham.com/">Website by RB Consulting</a></li>
      <li><a href="http://www.badham.com/erlend">Erlend</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <% logo = image_tag("logo.png", :alt => "Gliding On Ice", :class => "round") %>
  <%= link_to logo, root_path %>

  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Register", registration_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Admin", admin_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= title %></title>

    <%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
</head>
<body>
    <div class="container">
      <header>
		<%= render 'layouts/header' %>
      </header>
      <section class="round">
        <%= yield %>
      </section>
<%= render 'layouts/footer'%>
    </div>
</body>
</html>

app/views/pages/contact.html.erb
<h1>GLIDING ON ICE 2011®</h1>
<p>
	contact stuff
</p>

app/views/pages/home.html.erb
<p><br/>
   	Vi har gleden av å invitere din klubb til noen koordinerte aktivitetsdager på Steinsfjorden i Buskerud i mars. 
	Dette er ikke et stevne, men en happening!
	<br/>
</p>

app/views/pages/registration.html.erb
<h1>GLIDING ON ICE 2011®</h1>
<p>
   		Reg stuff
</p>